#!/bin/bash
notify-send -u critical -t 5000 "Starting Backup" "Attempting backup of TinyNozem to NASQ" && ionice -c3 nice -n19 $HOME/Scripts/backup/backup-tinynozem-to-nasq.sh
notify-send -u critical -t 5000 "Archiving Screenshots" && ionice -c3 nice -n19 $HOME/Scripts/file/screenshot-archiver.py
