#!/bin/bash
# Author: David Spreekmeester @aapit
vi "$(
  sk --ansi -i -c \
  '(\
    (rg -i --color=always --line-number "{}") &&
    (ls *.md | rg -i --color=always "{}")\
   ) |
   uniq --check-chars 15 | sort -S 50% --parallel=4 \
  '|sed -r 's/(.*)(:[0-9]+:).*/\1/'
)"
